apiVersion: v1
kind: Service
metadata:
  name: copa-frontend-lb
  namespace: copa-ticketing
  labels:
    app.kubernetes.io/name: copa-frontend
    app.kubernetes.io/part-of: oracle-ddd-demo
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: copa-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
